
## TWITTER CONFIG
BEARER_TOKEN = ''
TWITTER_USER_ID = '' # TWITTER USER ID TO FETCH FOLLOWERS

## MYSQL LOCAL CONFIG
MYSQL_HOST = ''
MYSQL_USER = ''
MYSQL_PASSWORD = ''
MYSQL_DATABASE = ''

## REMOTE MYSQL HOST CONFIG
REMOTE_MYSQL_HOST = ''
REMOTE_MYSQL_USER = ''
REMOTE_MYSQL_PASSWORD = ''
REMOTE_MYSQL_DATABASE = ''

## FREQUENCY CONFIGS

GET_AUTHOR_STATS_FREQUENCY = 60 # MINUTES

## FOLLOWERS
NEW_FOLLOWERS_FREQUENCY = 30 # seconds | NOT YET CONFIGURED IN SCRIPT
BUILD_FOLLOWERS_FREQUENCY = 30 # minutes
RETURNED_FOLLOWERS_COUNT = 200
SQL_QUERY_FREQUENCY = 20 # MINUTES


## SEARCH TWEETS
SEARCH_TWEETS_FREQUENCY = 3 # minutes
QUERY = ''
ADD_QUERY = ''

# UPDATES ROWS BASED ON INTERVAL
# EG: 6, 12, 1
# REFETCHES TWEETS IN ROWS THAT ARE BETWEEN 6 - 12 HOURS OLD BASED ON TIMESTAMP
# THEN TAG 1 ON THE "UPDATED" COLUMN AND THE UPDATE TIME ON "UPDATED_TIME" COLUMN
# -1 is either deleted tweet or from a suspended account
SEARCH_UPDATE_INTERVAL = [
    (4, 8, 1),
    (8, 12, 2),
    (12, 24, 3),
    (24, 48, 4),
    (96, 192, 5),
]